In [1]:
import pandas as pd
import glob

In [64]:
def get_stops_from_log(path):
    main_df = pd.DataFrame()
    for file in glob.glob(path):
        print(file)
        df = pd.read_csv(file)
        date = df.columns[-1]
        df = df.reset_index()
        df.columns = df.iloc[0]
        df = df.drop(0)
        df = df[['Station type', 'Time', 'Latitude', 'Longitude', 'Comment']]
        df['Date'] = date
        if main_df.empty:
            main_df = df
        else:
            main_df = pd.concat([main_df,df])
    
    main_df['Datetime'] = pd.to_datetime(main_df['Date'] + " " + main_df['Time'])
    main_df['Date'] = pd.to_datetime(main_df['Date'])
    main_df = main_df.drop(columns=['Time'])
    
    return main_df

In [65]:
leg2_stops = get_stops_from_log("/Users/maritlund/Documents/Skole/Master/leg2_log/ref*.csv")
leg3_stops = get_stops_from_log("/Users/maritlund/Documents/Skole/Master/leg3_log/ref*.csv")
main_df = pd.concat([leg2_stops, leg3_stops])
main_df = main_df.sort_values(by="Datetime")

/Users/maritlund/Documents/Skole/Master/leg2_log/ref13-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref13-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref21-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref21-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref06-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref06-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref28-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref28-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref31-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref03-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref03-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref16-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref16-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref24-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref24-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref09-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref09-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref27-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref27-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref15-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref15-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref05-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref05-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref19-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref19-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref22-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref22-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref10-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref10-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref30-09-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref25-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref25-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref17-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref17-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref02-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref02-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref30-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref07-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref07-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref29-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref20-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref20-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref12-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref12-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref11-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref11-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref23-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref23-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref18-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref18-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref04-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref04-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref01-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref01-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref14-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref14-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref08-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref08-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref26-10-2021.csv
/Users/maritlund/Documents/Skole/Master/leg2_log/ref26-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref12-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref07-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref28-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref02-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref17-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref27-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref14-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref08-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref01-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref04-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref11-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref16-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref30-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref03-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref29-11-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref06-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref13-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref10-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref05-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref09-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref15-12-2021.csv
/Users/maritlund/Documents/Skole/Master/leg3_log/ref26-11-2021.csv

In [66]:
main_df = main_df.dropna()
main_df
main_df.Datetime = main_df['Datetime'].dt.round('30min') 
main_df

,Station type,Latitude,Longitude,Comment,Date,Datetime
1,Watersample start,2755.779477 N,01520.353045 W,,2021-04-10,2021-10-04 15:30:00
2,Watersample stop,2741.100371 N,01536.289008 W,,2021-04-10,2021-10-04 18:00:00
3,Other,2740.544524 N,01538.368087 W,Sj�pattedyr observasjon,2021-04-10,2021-10-04 18:30:00
5,Other,2739.689633 N,01541.583867 W,Vannisotop,2021-04-10,2021-10-04 19:00:00
1,Other,2724.300524 N,01632.497918 W,Vannisotop,2021-05-10,2021-10-05 07:00:00
...,...,...,...,...,...,...
6,Other,3802.457946 N,07340.450189 W,Fishing,2021-12-16,2021-12-16 14:00:00
8,Other,3809.878517 N,07337.121373 W,Vannisotop,2021-12-16,2021-12-16 15:00:00
16,Other,3841.414446 N,07336.979429 W,Sj�pattedyr observasjon,2021-12-16,2021-12-16 21:30:00
2,Other,3931.622929 N,07338.786179 W,Vannisotop,2021-12-17,2021-12-17 04:00:00
4,Other,4028.659187 N,07353.135006 W,Vannisotop,2021-12-17,2021-12-17 14:30:00

In [67]:
stops = main_df[main_df['Station type'].str.upper().str.contains('CTD')]
stops

,Station type,Latitude,Longitude,Comment,Date,Datetime
6,CTD start,1716.002079 N,02530.042391 W,"secchi, trawl & CTD",2021-10-10,2021-10-10 10:30:00
7,CTD stop,1716.071574 N,02530.691023 W,"secchi, trawl & CTD",2021-10-10,2021-10-10 12:00:00
11,CTD start,1138.455356 N,03640.459520 W,"CTD, secchi disk and plankton trawl",2021-10-15,2021-10-15 16:00:00
12,CTD stop,1139.735895 N,03643.672153 W,"CTD, secchi disk and plankton trawl",2021-10-15,2021-10-15 17:00:00
7,CTD start,1316.515140 N,05800.337303 W,"ctd, plankton trawl and secchi disk",2021-10-24,2021-10-24 16:00:00
8,CTD stop,1318.296266 N,05801.727841 W,"ctd, plankton trawl and secchi disk",2021-10-24,2021-10-24 17:30:00
8,CTD start,1310.705234 N,06608.418944 W,CTD and plankton trawl and secchi disk,2021-10-31,2021-10-31 16:00:00
9,CTD stop,1310.421319 N,06609.949979 W,CTD and plankton trawl and secchi disk,2021-10-31,2021-10-31 17:30:00
11,CTD start,1228.118951 N,06618.794772 W,,2021-01-11,2021-11-01 16:30:00
12,CTD stop,1227.817531 N,06619.532222 W,,2021-01-11,2021-11-01 17:30:00
11,CTD start,1312.457876 N,07032.632949 W,"CTD, secchi, plankton trawl + field course mea...",2021-09-11,2021-11-09 18:30:00
12,CTD stop,1313.950132 N,07037.031084 W,"CTD, secchi, plankton trawl + field course mea...",2021-09-11,2021-11-09 21:00:00
10,CTD start,1434.481712 N,07228.101256 W,only CTD and secchi,2021-10-11,2021-11-10 20:00:00
11,CTD stop,1435.147920 N,07230.099516 W,only CTD and secchi,2021-10-11,2021-11-10 21:30:00
8,CTD start,1642.204531 N,07601.370444 W,"CTD, plankton, secchi and field course histori...",2021-12-11,2021-11-12 20:30:00
9,CTD stop,1640.717250 N,07603.151331 W,"CTD, plankton, secchi and field course histori...",2021-12-11,2021-11-12 22:00:00
11,CTD start,1740.486987 N,07750.836587 W,"ctd, secchi, plankton trawl",2021-11-18,2021-11-18 19:30:00
12,CTD stop,1740.138130 N,07750.535911 W,"ctd, secchi, plankton trawl",2021-11-18,2021-11-18 20:30:00

In [61]:
df = pd.read_csv('sensors_log_match.csv')

In [63]:
stops.merge(df, left_on='Date', right_on='date', how='inner')

KeyError: 'Date'